# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlowerPower' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlowerPower
    pod "PromiseKit", "~> 6.8"
    pod 'AlamofireImage', '~> 4.1'
    pod "PromiseKit/CoreLocation", "~> 6.0"
end
